### ISSUE TITLE
environment.yml takes too long to solve

### ISSUE THREAD

**Issue by sditkovsky** [ClimateMatchAcademy/course-content#277]
I'm trying to make a conda environment from the `environment.yml` file, but the dependencies seem too complicated for conda to solve. I left the command running for ~24 hours and it still had not solved the environment. But let me know if this hasn't been a problem on other machines...

Are all of the dependencies in the file used for the tutorials? We could try to trim it down as much as possible.

**Comment by jlpearso** [comment]
Hi Sam, thank you for leaving this comment! Our content has actually been merged with the Neuromatch organization GitHub: https://github.com/neuromatch/climate-course-content

The fork you work on materials from should be from there (our curriculum chair has contacted all day leads today to make sure this is the cases it may have been glossed over in the many instructions).

In the environment file on the other repository you should be able to uncomment the python=3.9 line, and if you use mamba instead of conda it tends to be faster: `mamba env create -f environment.yml`

you may run into issues with cis and ecco_v4_py packages depending on what computer you are using. I do not believe those are used in W2D1 at all so you should be fine to comment those out. If you have any other issues please don't hesitate to open an issue over on the other GitHub repo.

**Comment by sditkovsky** [comment]
Thanks Jenna! I'll try this out
